export type LeadStatus =
  | 'new'
  | 'contacted'
  | 'consultation_scheduled'
  | 'nurturing'
  | 'proposal_submitted'
  | 'proposal_declined'
  | 'proposal_accepted'
  | 'estimate_submitted'
  | 'estimate_declined'
  | 'estimate_accepted'
  | 'accepted'
  | 'declined'
  | 'converted'
  | 'closed_unbooked';
