import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ActivatedRoute, Router } from '@angular/router';
import { CustomerPaymentService } from '../../../core/supabase/services/customer-payment.service';
import { PaymentOptionsComponent } from './payment-options.component';

describe('PaymentOptionsComponent',()=>{
  let fixture:ComponentFixture<PaymentOptionsComponent>;let component:PaymentOptionsComponent;let payments:jasmine.SpyObj<CustomerPaymentService>;
  beforeEach(async()=>{payments=jasmine.createSpyObj('CustomerPaymentService',['resolve','choose','loadPayPalSdk','captureVenmo']);payments.resolve.and.resolveTo({state:'active',purpose:'consolidated',projectLabel:'Avery & Jordan',principalCents:10000,depositCents:3000,finalCents:7000,methods:['venmo','stripe_card','cash','check'],instructionSnapshots:{cash:'Call us',check:'Mail check'}});await TestBed.configureTestingModule({imports:[PaymentOptionsComponent],providers:[{provide:CustomerPaymentService,useValue:payments},{provide:ActivatedRoute,useValue:{snapshot:{paramMap:{get:()=> 'opaque'}}}},{provide:Router,useValue:{navigate:jasmine.createSpy('navigate')}}]}).compileComponents();fixture=TestBed.createComponent(PaymentOptionsComponent);component=fixture.componentInstance;await component.ngOnInit();fixture.detectChanges();});
  it('renders one fixed amount, consolidated breakdown, fee disclosure, and four branded methods',()=>{const text=fixture.nativeElement.textContent;expect(text).toContain('Payment Methods');expect(text).toContain('Amount Due');expect(text).toContain('$100.00');expect(text).toContain('Deposit $30.00');expect(text).toContain('Final payment $70.00');expect(text).toContain('fees are absorbed');expect(fixture.nativeElement.querySelectorAll('.methods button').length).toBe(4);expect(fixture.nativeElement.querySelectorAll('.method-icon').length).toBe(4);});
  it('renders the Black Begonia floral image behind the payment card',()=>{const image=fixture.nativeElement.querySelector('.payment-background') as HTMLImageElement;const card=fixture.nativeElement.querySelector('.payment-card');expect(image).not.toBeNull();expect(image.getAttribute('src')).toBe('assets/images/website/E-T-849.webp');expect(image.alt).toBe('Black Begonia floral arrangement');expect(card).not.toBeNull();});
  it('replaces payment methods with a cash coordination confirmation',async()=>{payments.choose.and.resolveTo({kind:'intention',method:'cash',instructions:'Call us',pauseEndsAt:'2026-08-01T00:00:00Z'});await component.choose('cash');fixture.detectChanges();const text=fixture.nativeElement.textContent;expect(component.projection().intention?.method).toBe('cash');expect(component.confirmationMethod()).toBe('cash');expect(text).toContain('preferred payment method of paying by cash has been recorded');expect(text).toContain('preferred date, time, and location');expect(text).toContain('not yet been marked as paid');expect(fixture.nativeElement.querySelector('.cash-confirmation')).not.toBeNull();expect(fixture.nativeElement.querySelector('.methods')).toBeNull();});
  it('replaces payment methods with a populated instructional demo check',async()=>{component.projection.update(value=>({...value,eventDate:'2026-09-12'}));payments.choose.and.resolveTo({kind:'intention',method:'check',instructions:'Mail check',pauseEndsAt:'2026-08-01T00:00:00Z'});await component.choose('check');fixture.detectChanges();const text=fixture.nativeElement.textContent;expect(component.confirmationMethod()).toBe('check');expect(text).toContain('preferred payment method of paying by check has been recorded');expect(text).toContain('Black Begonia Floral Designs, LLC');expect(text).toContain('$100.00');expect(text).toContain('One hundred and 00/100 dollars');expect(text).toContain('Project payment - Event 9/12/2026');expect(text).not.toContain('Avery & Jordan payment');expect(text).toContain('within one week of signing your agreement');expect(text).toContain('In the memo line, write your event date');expect(text).toContain('Your signature');expect(fixture.nativeElement.querySelector('.demo-check')).not.toBeNull();expect(fixture.nativeElement.querySelector('.methods')).toBeNull();});

  it('spells a multi-thousand-dollar check amount',()=>{expect(component.amountInWords(204349)).toBe('Two thousand forty-three and 49/100 dollars');});
  it('shows an inaccessible-link state without payment controls',()=>{component.projection.set({state:'unavailable'});fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('payment link is unavailable');expect(fixture.nativeElement.querySelector('.methods')).toBeNull();});
  it('exposes keyboard-native method buttons and a live status region',()=>{expect(fixture.nativeElement.querySelector('section[aria-live="polite"]')).not.toBeNull();const buttons=[...fixture.nativeElement.querySelectorAll('.methods button')] as HTMLButtonElement[];expect(buttons.every(button=>button.tabIndex>=0)).toBeTrue();});
  it('orchestrates eligible Venmo approval through server capture',async()=>{let options:any;const navigate=(TestBed.inject(Router).navigate as jasmine.Spy);(globalThis as any).paypal={FUNDING:{VENMO:'venmo'},Buttons:(value:any)=>{options=value;return{render:()=>Promise.resolve()};}};payments.choose.and.resolveTo({kind:'paypal_order',orderId:'ORDER',attempt:'ATTEMPT',clientId:'CLIENT'});payments.loadPayPalSdk.and.resolveTo();payments.captureVenmo.and.resolveTo({state:'processing'});await component.choose('venmo');expect(options.createOrder()).toBe('ORDER');await options.onApprove();expect(payments.captureVenmo).toHaveBeenCalledWith('opaque','ATTEMPT');expect(navigate).toHaveBeenCalled();delete (globalThis as any).paypal;});
  it('keeps the balance outstanding for Venmo cancellation and provider errors',async()=>{let options:any;(globalThis as any).paypal={FUNDING:{VENMO:'venmo'},Buttons:(value:any)=>{options=value;return{render:()=>Promise.resolve()};}};payments.choose.and.resolveTo({kind:'paypal_order',orderId:'ORDER',attempt:'ATTEMPT',clientId:'CLIENT'});payments.loadPayPalSdk.and.resolveTo();await component.choose('venmo');options.onCancel();expect(component.error()).toContain('still outstanding');options.onError();expect(component.error()).toContain('another method');delete (globalThis as any).paypal;});
});
