import { TestBed } from '@angular/core/testing';
import { Router } from '@angular/router';
import { PaymentRepositoryService } from '../../../../../core/supabase/repositories/payment-repository.service';
import { PaymentObligationModalComponent } from './payment-obligation-modal.component';
describe('PaymentObligationModalComponent',()=>{
  const detail:any={obligation:{payment_kind:'deposit',status:'due',target_amount:300,credited_principal:100,outstanding_amount:200,basis_version:2},project:{project_id:'project',project_name:'Avery Event'},requests:[],checkouts:[],intentions:[],transactions:[{payment_reference:'BBP-2026-1',kind:'receipt',method:'stripe',principal_amount:100,customer_fee:0,merchant_fee:3,occurred_at:'2026-01-01'}],deliveries:[],exceptions:[{payment_exception_id:'exception',exception_type:'overpayment',summary:'Review credit',state:'open'}],legalHolds:[],activity:[]};
  async function setup(){const repository=jasmine.createSpyObj('PaymentRepositoryService',['getObligationDetail','setLegalHold','revokeRequest','setObligationState','resolveException']);repository.getObligationDetail.and.resolveTo(detail);repository.setLegalHold.and.resolveTo({} as any);const navigate=jasmine.createSpy();await TestBed.configureTestingModule({imports:[PaymentObligationModalComponent],providers:[{provide:PaymentRepositoryService,useValue:repository},{provide:Router,useValue:{navigate}}]}).compileComponents();const fixture=TestBed.createComponent(PaymentObligationModalComponent);fixture.componentInstance.obligationId='deposit';await fixture.componentInstance.ngOnInit();fixture.detectChanges();return{fixture,component:fixture.componentInstance,repository,navigate};}
  it('renders ordered histories, separate fees, references, exceptions, and no secrets',async()=>{const{fixture}=await setup();const text=fixture.nativeElement.textContent;expect(text).toContain('BBP-2026-1');expect(text).toContain('Merchant fee $3.00');expect(text).toContain('Review credit');expect(text).not.toContain('token_ciphertext');});
  it('requires a hold reason and records authorized place/release actions',async()=>{const{component,repository}=await setup();component.holdReason='';await component.saveHold();expect(repository.setLegalHold).not.toHaveBeenCalled();component.holdReason='Charge disputed';component.holdAction='placed';await component.saveHold();expect(repository.setLegalHold).toHaveBeenCalledWith('project','placed','dispute','Charge disputed',jasmine.any(String));});
  it('navigates to the project and emits close',async()=>{const{component,navigate}=await setup();const closed=jasmine.createSpy();component.closed.subscribe(closed);component.openProject();expect(closed).toHaveBeenCalled();expect(navigate).toHaveBeenCalledWith(['/admin/projects','project']);});
  it('uses modal semantics and an accessible close control',async()=>{const{fixture}=await setup();expect(fixture.nativeElement.querySelector('[role="dialog"][aria-modal="true"]')).not.toBeNull();expect(fixture.nativeElement.querySelector('button[aria-label="Close payment details"]')).not.toBeNull();});
});
